name: Node CI

on: [push,pull_request]

jobs:
  container-job:

    runs-on: ubuntu-latest

    container:
      image:  node:latest

    services:
      mongo:
        image: mongo:4.2.0
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        npm install --unsafe-perm
        npm test
      env:
        CI: true
        NODE_ENV: test
        MONGODB_URI: mongodb://mongo:${{ job.services.mongo.ports[27017] }}/app-test
